#if ALL_TESTS

namespace KarambaCommon.Tests.Algorithms
{
    using System.Collections.Generic;
    using Karamba.CrossSections;
    using Karamba.Elements;
    using Karamba.Geometry;
    using Karamba.Loads;
    using Karamba.Materials;
    using Karamba.Supports;
    using Karamba.Utilities;
    using KarambaCommon;
    using NUnit.Framework;

    [TestFixture]
    public class DeformThII_tests
    {
        [Test]
        public void Column()
        {
            Toolkit k3d = new Toolkit();
            MessageLogger logger = new MessageLogger();
            double length = 4.0;
            Point3 p0 = new Point3(0, 0, 0);
            Point3 p1 = new Point3(0, 0, length);
            Line3 axis = new Line3(p0, p1);

            // get a cross section from the cross section table in the folder 'Resources'
            CroSec_Trapezoid crosec = new CroSec_Trapezoid(
                "family",
                "name",
                "country",
                null,
                Material_Default.Instance().steel,
                20,
                10,
                10);
            crosec.Az = 1E10; // make it stiff in shear

            // create the column
            List<BuilderBeam> beams = k3d.Part.LineToBeam(
                new List<Line3> { axis },
                new List<string>() { "B1" },
                new List<CroSec>() { crosec },
                logger,
                out List<Point3> out_points);

            // create supports
            List<Support> supports = new List<Support>
            {
                k3d.Support.Support(p0, new List<bool>() { true, true, true, true, true, true }),
            };

            // create a Point-load
            int fz = 10;
            List<Load> loads = new List<Load> { k3d.Load.PointLoad(p1, new Vector3(0, 0, -fz)), };

            // create the model
            var model = k3d.Model.AssembleModel(
                beams,
                supports,
                loads,
                out var info,
                out var mass,
                out var cog,
                out var message,
                out var warning);

            // calculate Th.II response
            model = k3d.Algorithms.AnalyzeThII(
                model,
                "0",
                1E-7,
                50,
                true,
                out var out_max_disp,
                out var out_g,
                out var out_comp,
                out message);

            var ea = crosec.material.E() * crosec.A;
            var maxDispTarg = fz * length / ea;

            // check the buckling length,; a negative value means that the length was autogenerated
            Assert.That(out_max_disp[0], Is.EqualTo(maxDispTarg).Within(1E-10));
        }
    }
}

#endif